### ISSUE TITLE
Getting access denied after choosing bank in net banking payment option

### ISSUE THREAD

**Issue by madhavbhattarai** [citruspay/citrus-android-sdk#22]
I updated the citrus SDK from version 3.4.3 to 3.6.2 and now facing this issue. Backward compatibility should have been maintained.

![screenshot_2016-08-12-11-52-24](https://cloud.githubusercontent.com/assets/5369991/17614622/50b89f0c-6085-11e6-9716-e4c9c88ee693.png)

**Comment by madhavbhattarai** [comment]
I updated the citrus SDK from version 3.4.2 to  3.6.2 and now facing this issue. Backward compatibility should have been maintained.

**Comment by salilgodbole** [comment]
Hi Madhav,

This issue is not related to SDK version. Citrus SDK is always backward
compatible.
The access denied error occurs when there is some issue at the PG level.

Can you please try after sometime?
Also send us details like which environment you are using and merchant name.
Please drop an email to developer.support@citruspay.com, keeping
mobiledev@citruspay.com in cc.

Thanks,
Salil

**Comment by madhavbhattarai** [comment]
I emailed you the details along with merchant name. For your information, I am using the same credentials that I have been using in the previous sdk version.

**Comment by madhavbhattarai** [comment]
I verified the credentials and other setups. Still, I am getting the same error. Please pinpoint, what might be the reason for this "access denied" message.
